# Generated by Django 3.1.5 on 2021-01-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webb', '0003_auto_20210130_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
