# Generated by Django 3.1.5 on 2021-01-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webb', '0004_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
